# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  mysql:
    image: mysql:8.0
    volumes:
      - ahead-data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ahead_db
    depends_on:
      - server

  server:
#    build: .
    image: kandan200/ahead-ahead
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - mysql

      #for automatic reloading of app when changes are made to source code
#develop:
 #     watch:
  #      - action: rebuild
   #       path: .

#volumes:
#  ahead-data:
#    driver: local
