apiVersion: v1
kind: Pod
metadata:
  name: ahead-pod
  labels:
    name: ahead-pod
spec:
  containers:
  - name: mysql
    image: mysql:8.0
  - name: server
    image: kandan200/ahead-ahead
    command: ['bash', '-c', "python", 'manage.py', 'makemigrations', '&&', 'python', 'manage.py', 'migrate', '&&', 'python', 'manage.py', 'runserver', "0.0.0.0:8000"]
  
#  initContainers:
#  - name: init-myservice
#    image: busybox:1.28
#    command: ['sh', '-c', "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
#  - name: init-mydb
#    image: busybox:1.28
#    command: ['sh', '-c', "until nslookup mydb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done"]