# Generated by Django 4.1.6 on 2023-02-23 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctore',
            fields=[
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to say')], max_length=20)),
                ('specialty', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(null=True)),
                ('mdcn', models.IntegerField(default=123, primary_key=True, serialize=False)),
                ('state_of_residence', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Doctor Profile',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('sample_size', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docApp.doctore')),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('facility', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to say')], max_length=20)),
                ('education', models.CharField(choices=[('N', 'None'), ('P', 'Primary'), ('S', 'Secondary'), ('T', 'Tertiary')], max_length=50)),
                ('occupation', models.CharField(max_length=100)),
                ('tribe', models.CharField(max_length=50)),
                ('presentation_date', models.DateField()),
                ('diagnosis', models.CharField(max_length=200)),
                ('adnission', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docApp.research')),
            ],
        ),
    ]
