# Generated by Django 4.1.6 on 2023-02-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='mdcn_registration_number',
            new_name='mdcn_folio_number',
        ),
    ]
