# Generated by Django 4.1.6 on 2023-02-28 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docApp', '0002_alter_doctore_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='research',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docApp.research'),
        ),
        migrations.AlterField(
            model_name='research',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docApp.doctore'),
        ),
    ]
