# Generated by Django 4.1.6 on 2023-02-14 02:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docApp', '0002_rename_mdcn_registration_number_signup_mdcn_folio_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='age',
        ),
        migrations.AddField(
            model_name='signup',
            name='certificate',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='signup',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='state_of_residence',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='year_of_graduation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
