# Generated by Django 4.1.6 on 2023-02-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docApp', '0003_alter_participants_research_alter_research_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctore',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctore',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='doctore',
            name='state_of_residence',
            field=models.CharField(max_length=30),
        ),
    ]
