# Generated by Django 4.1.6 on 2023-02-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docApp', '0004_alter_signup_year_of_graduation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField(null=True)),
                ('sex', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(null=True)),
                ('mdcn_folio_number', models.IntegerField()),
                ('state_of_residence', models.CharField(max_length=30, null=True)),
                ('year_of_graduation', models.DateTimeField(null=True)),
                ('certificate', models.FileField(null=True, upload_to='')),
                ('avatar', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
