# Generated by Django 4.1.6 on 2023-03-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docApp', '0004_alter_doctore_password_alter_doctore_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctore',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='doctore',
            name='firstName',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='doctore',
            name='lastName',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='doctore',
            name='mdcn',
            field=models.IntegerField(default=123, primary_key=True, serialize=False, verbose_name='MDCN Folio Number'),
        ),
        migrations.AlterField(
            model_name='doctore',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='doctore',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='doctore',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to say')], max_length=20, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='doctore',
            name='specialty',
            field=models.CharField(max_length=100, verbose_name='Specialty'),
        ),
        migrations.AlterField(
            model_name='doctore',
            name='state_of_residence',
            field=models.CharField(max_length=30, verbose_name='State of Residence'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='adnission',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, verbose_name='Admission Status'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='diagnosis',
            field=models.CharField(max_length=200, verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='education',
            field=models.CharField(choices=[('N', 'None'), ('P', 'Primary'), ('S', 'Secondary'), ('T', 'Tertiary')], max_length=50, verbose_name='Level of Education'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='facility',
            field=models.CharField(max_length=200, verbose_name='Healthcare Facility'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Participant ID'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='occupation',
            field=models.CharField(max_length=100, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='presentation_date',
            field=models.DateField(verbose_name='Date of Presentation'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to say')], max_length=20, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='tribe',
            field=models.CharField(max_length=50, verbose_name='Tribe'),
        ),
        migrations.AlterField(
            model_name='research',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Research ID'),
        ),
        migrations.AlterField(
            model_name='research',
            name='sample_size',
            field=models.IntegerField(verbose_name='Research Sample Size'),
        ),
        migrations.AlterField(
            model_name='research',
            name='start_date',
            field=models.DateField(verbose_name='Research Start Date'),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Research Title'),
        ),
    ]
