# Generated by Django 4.1.6 on 2023-03-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docApp', '0005_alter_doctore_email_alter_doctore_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Participant ID'),
        ),
    ]
