# Generated by Django 4.1.6 on 2023-02-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docApp', '0005_userprofile_delete_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to say')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='User Profile',
        ),
    ]
