# Generated by Django 4.1.6 on 2023-02-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docApp', '0006_alter_userprofile_sex_alter_userprofile_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mdcn_folio_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='year_of_graduation',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mdcn',
            field=models.IntegerField(default=123, primary_key=True, serialize=False, unique=True),
        ),
    ]
