# Generated by Django 4.1.6 on 2023-03-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docApp', '0006_alter_participants_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctore',
            name='confirm_password',
            field=models.CharField(default=123, max_length=100, verbose_name='Password'),
            preserve_default=False,
        ),
    ]
