# Generated by Django 4.1.6 on 2023-02-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docApp', '0007_remove_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mdcn',
            field=models.IntegerField(default=123, primary_key=True, serialize=False),
        ),
    ]
